import type { Table } from './components/TableCard';

export const AVAILABLE_SERVERS = [
    { value: 'server_a', label: 'Nguyễn Văn A' },
    { value: 'server_b', label: 'Trần Thị B' },
    { value: 'server_c', label: 'Lê Văn C' },
    { value: 'server_d', label: 'Phạm Thị D' },
];

export const INITIAL_TABLES: Table[] = [
    {
        _id: 'table-01',
        number: '01',
        status: 'occupied',
        shape: 'rectangular',
        capacity: 4,
        currentOccupancy: 3,
        assignedServer: 'Nguyễn Văn A',
        orderId: 'OD1250',
        x: 90,
        y: 60,
    },
    {
        _id: 'table-02',
        number: '02',
        status: 'available',
        shape: 'rectangular',
        capacity: 4,
        currentOccupancy: 0,
        x: 260,
        y: 60,
    },
    {
        _id: 'table-03',
        number: '03',
        status: 'reserved',
        shape: 'circular',
        capacity: 6,
        currentOccupancy: 0,
        assignedServer: 'Lê Văn C',
        x: 430,
        y: 60,
    },
    {
        _id: 'table-04',
        number: '04',
        status: 'available',
        shape: 'rectangular',
        capacity: 2,
        currentOccupancy: 0,
        x: 600,
        y: 60,
    },
    {
        _id: 'table-05',
        number: '05',
        status: 'cleaning',
        shape: 'rectangular',
        capacity: 4,
        currentOccupancy: 0,
        assignedServer: 'Trần Thị B',
        x: 770,
        y: 60,
    },
    {
        _id: 'table-06',
        number: '06',
        status: 'occupied',
        shape: 'circular',
        capacity: 8,
        currentOccupancy: 7,
        assignedServer: 'Phạm Thị D',
        orderId: 'OD1251',
        x: 90,
        y: 220,
    },
    {
        _id: 'table-07',
        number: '07',
        status: 'available',
        shape: 'rectangular',
        capacity: 4,
        currentOccupancy: 0,
        x: 260,
        y: 220,
    },
    {
        _id: 'table-08',
        number: '08',
        status: 'occupied',
        shape: 'rectangular',
        capacity: 4,
        currentOccupancy: 4,
        assignedServer: 'Nguyễn Văn A',
        orderId: 'OD1260',
        x: 430,
        y: 220,
    },
    {
        _id: 'table-09',
        number: '09',
        status: 'available',
        shape: 'circular',
        capacity: 2,
        currentOccupancy: 0,
        x: 600,
        y: 220,
    },
    {
        _id: 'table-10',
        number: '10',
        status: 'reserved',
        shape: 'rectangular',
        capacity: 6,
        currentOccupancy: 0,
        x: 770,
        y: 220,
    },
];
