import type { FeedPost, NearbyRestaurant } from "./types"

export const MOCK_NEARBY_RESTAURANTS: NearbyRestaurant[] = [
  {
    id: "r1",
    name: "Bep Nuong Pho Co",
    image: "/assets/home/9j_4AAQSk.jpg",
    rating: 4.8,
    distance: "1.2 km",
    verified: true,
    provinceCode: 1,
    districtCode: 1,
  },
  {
    id: "r2",
    name: "Pho 24 Signature",
    image: "/assets/home/9j_4AAQSk_2.jpg",
    rating: 4.7,
    distance: "2.1 km",
    verified: true,
    provinceCode: 1,
    districtCode: 2,
  },
  {
    id: "r3",
    name: "Coffee District 1",
    image: "/assets/home/9j_4AAQSk_3.jpg",
    rating: 4.6,
    distance: "900 m",
    verified: false,
    provinceCode: 79,
    districtCode: 1,
  },
  {
    id: "r4",
    name: "Da Nang Seafood Hub",
    image: "/assets/home/image.png",
    rating: 4.9,
    distance: "3.4 km",
    verified: true,
    provinceCode: 48,
    districtCode: 1,
  },
]

export const MOCK_POSTS: FeedPost[] = [
  {
    id: "p1",
    type: "promotion",
    restaurant: {
      name: "Bep Nuong Pho Co",
      avatar: "/assets/home/9j_4AAQSk.jpg",
      verified: true,
      location: "Hoan Kiem",
      provinceCode: 1,
      districtCode: 1,
    },
    timestamp: "2 gio truoc",
    content:
      "Combo nuong cuoi tuan giam manh cho nhom ban. Dat ban online de giu uu dai den het ngay Chu Nhat.",
    tags: ["buffet", "nuong", "khuyenmai"],
    promotion: {
      discount: "30%",
      validUntil: "30/04/2026",
    },
    images: [
      "/assets/home/9j_4AAQSk.jpg",
      "/assets/home/9j_4AAQSk_2.jpg",
      "/assets/home/9j_4AAQSk_3.jpg",
    ],
    liked: false,
    bookmarked: false,
    likes: 1240,
    comments: 128,
    shares: 52,
  },
  {
    id: "p2",
    type: "new_menu",
    restaurant: {
      name: "Pho 24 Signature",
      avatar: "/assets/home/9j_4AAQSk_2.jpg",
      verified: true,
      location: "Ba Dinh",
      provinceCode: 1,
      districtCode: 2,
    },
    timestamp: "4 gio truoc",
    content:
      "Ra mat menu pho bo wagyu va pho ga collagen. Nuoc dung trong, ngot tu nhien va phu hop ca bua trua nhanh.",
    tags: ["menu-moi", "pho", "amthucviet"],
    images: ["/assets/home/image.png"],
    liked: true,
    bookmarked: false,
    likes: 980,
    comments: 86,
    shares: 31,
  },
  {
    id: "p3",
    type: "feedback",
    restaurant: {
      name: "Coffee District 1",
      avatar: "/assets/home/iVBORw0KGg.png",
      verified: false,
      location: "Quan 1",
      provinceCode: 79,
      districtCode: 1,
    },
    timestamp: "6 gio truoc",
    content:
      "Khong gian yen tinh cho lam viec va gap go ban be. Do uong len nhanh, nhan vien than thien va tu van nhiet tinh.",
    tags: ["review", "coffee", "workspace"],
    customerFeedback: {
      name: "Le Minh Thu",
      avatar: "/assets/home/emily.png",
      rating: 5,
      comment: "Do uong ngon, khong gian dep va phuc vu rat de chiu.",
    },
    images: [
      "/assets/home/iVBORw0KGg_2.png",
      "/assets/home/iVBORw0KGg_3.png",
    ],
    liked: false,
    bookmarked: true,
    likes: 756,
    comments: 64,
    shares: 18,
  },
  {
    id: "p4",
    type: "event",
    restaurant: {
      name: "Da Nang Seafood Hub",
      avatar: "/assets/home/iVBORw0KGg_4.png",
      verified: true,
      location: "Hai Chau",
      provinceCode: 48,
      districtCode: 1,
    },
    timestamp: "8 gio truoc",
    content:
      "Dem nhac acoustic ket hop set hai san dac biet. So luong cho ngoi gioi han, nen dat truoc de uu tien vi tri dep.",
    tags: ["su-kien", "acoustic", "haisan"],
    event: {
      price: "299K",
      time: "19:00 - 22:00",
      special: "Free mocktail",
    },
    images: [
      "/assets/home/iVBORw0KGg_5.png",
      "/assets/home/9j_4AAQSk_3.jpg",
      "/assets/home/9j_4AAQSk_2.jpg",
      "/assets/home/9j_4AAQSk.jpg",
    ],
    liked: false,
    bookmarked: false,
    likes: 1412,
    comments: 203,
    shares: 94,
  },
  {
    id: "p5",
    type: "experience",
    restaurant: {
      name: "Kitchen Lab 92",
      avatar: "/assets/home/image.png",
      verified: true,
      location: "Ninh Kieu",
      provinceCode: 92,
      districtCode: 1,
    },
    timestamp: "10 gio truoc",
    content:
      "Chia se kinh nghiem setup quy trinh phuc vu gio cao diem: tach line order, gom mon theo khu vuc va toi uu check-list bep.",
    tags: ["kinh-nghiem", "quan-ly", "fnb"],
    liked: false,
    bookmarked: false,
    likes: 534,
    comments: 42,
    shares: 27,
  },
]
